# Generated by Django 5.0 on 2023-12-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_cloth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cloth_type',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids'), ('B', 'Books')], default='NA', max_length=30),
        ),
    ]
